name: Azure Bicep Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: Cloud_Computing
          template: ./main.bicep
          parameters: |
            location='eastus'
            adminUsername='${{ secrets.ADMIN_USERNAME }}'
            adminPassword='${{ secrets.ADMIN_PASSWORD }}'

          
