name: Deploy Azure Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.bicep'
      - '**/*.json'
      - '.github/workflows/deploy-azure.yml'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.bicep'
      - '**/*.json'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: |
          az bicep install
          az bicep version

      - name: Validate Bicep deployment
        run: |
          az deployment group validate \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file main.bicep \
            --parameters @main.parameters.json \
            --parameters adminPassword=${{ secrets.ADMIN_PASSWORD }}

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install Bicep CLI
        run: |
          az bicep install
          az bicep version

      - name: Create Resource Group if not exists
        run: |
          az group create \
            --name ${{ secrets.AZURE_RG }} \
            --location eastus

      - name: Deploy Infrastructure
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file main.bicep \
            --parameters @main.parameters.json \
            --parameters adminPassword=${{ secrets.ADMIN_PASSWORD }}
